spring:
  application:
    name: activitytracker





  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver


  #In memory
  datasource1:
    url: jdbc:h2:mem:activitytracker;MODE=MySQL
    username: user
    password:

    driver-class-name: org.h2.Driver


  # Hibernate/JPA settings
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true



what-to-answer-to-hw:
  answer: hello world (injected)


server:
  port: 8765
