spring:
  application:
    name: activitytracker

  # Database connection
  datasource:
    url: ${DB_URL:jdbc:h2:mem:ktornormal}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:}
    # MySQL driver

    # uncom the right one
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.h2.Driver


  # Hibernate/JPA settings
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true



what-to-answer-to-hw:
  answer: hello world (injected)


server:
  port: 8765
