services:
  server:
    container_name: tracker_server
    build:
      context: ../../../../
      dockerfile: src/main/resources/docker/Dockerfile
    pull_policy: build
    ports:
      - "8765:8765"
    restart: unless-stopped
